print("Hello this is Abhishek,Pranit and Sharmila's file")
print("Welcome ChachaSir to the group!!!!")
print("Sir you're not my CR")
print("Mrinal Gade you're my CR")
print("This is message from DBDA4")
print("Hello from DBDA Branch4")
